-- GearGuard initial schema, ported from the SQLite build.
--
-- Type choices worth knowing:
--  * Identity columns rather than AUTOINCREMENT, declared BY DEFAULT so seeds
--    and tests can still insert explicit ids.
--  * timestamptz, not timestamp. SQLite stored naive UTC strings, which the
--    client had to defensively re-parse (see client/src/services/datetime.js);
--    a zone-aware column removes that whole class of bug at the source.
--  * double precision for the operational metrics. numeric would be the right
--    type for money, but node-postgres returns numeric as a *string* to protect
--    precision, which would change every API response shape. Converting
--    cost_per_hour to numeric is a deliberate follow-up, not a silent change.

CREATE TABLE users (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        text NOT NULL,
  email       text NOT NULL UNIQUE,
  password    text NOT NULL,
  role        text NOT NULL DEFAULT 'user',
  avatar_url  text,
  created_at  timestamptz NOT NULL DEFAULT now()
);

-- Addresses are not case-sensitive in practice. Without this, "Alex@x.com" and
-- "alex@x.com" become two accounts that look identical at the login form.
-- Every route compares on lower(email), which this index also serves.
CREATE UNIQUE INDEX idx_users_email_nocase ON users (lower(email));

CREATE TABLE sessions (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  token_hash    text NOT NULL UNIQUE,
  csrf_token    text NOT NULL,
  user_id       integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  expires_at    timestamptz NOT NULL,
  created_at    timestamptz NOT NULL DEFAULT now(),
  last_seen_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_sessions_user_id ON sessions (user_id);
CREATE INDEX idx_sessions_expires_at ON sessions (expires_at);

CREATE TABLE audit_log (
  id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_user_id  integer REFERENCES users(id) ON DELETE SET NULL,
  action         text NOT NULL,
  resource_type  text NOT NULL,
  resource_id    text,
  metadata_json  text,
  created_at     timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_audit_log_actor ON audit_log (actor_user_id);
CREATE INDEX idx_audit_log_resource ON audit_log (resource_type, resource_id);
-- The trail is read newest-first and paged; this is the index that serves it.
CREATE INDEX idx_audit_log_created_at ON audit_log (created_at DESC, id DESC);

-- Only the SHA-256 hash of a reset token is stored, so a database leak cannot
-- be replayed against the reset endpoint.
CREATE TABLE password_reset_tokens (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  token_hash  text NOT NULL UNIQUE,
  user_id     integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  expires_at  timestamptz NOT NULL,
  used_at     timestamptz,
  created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_password_reset_expires ON password_reset_tokens (expires_at);
CREATE INDEX idx_reset_tokens_user ON password_reset_tokens (user_id);

CREATE TABLE teams (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        text NOT NULL UNIQUE,
  created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE team_members (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id     integer NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
  user_id     integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at  timestamptz NOT NULL DEFAULT now(),
  UNIQUE (team_id, user_id)
);

CREATE INDEX idx_team_members_user ON team_members (user_id);

CREATE TABLE equipment (
  id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name                    text NOT NULL,
  serial_number           text NOT NULL UNIQUE,
  category                text,
  department              text,
  assigned_employee_name  text,
  purchase_date           date,
  warranty_end_date       date,
  location                text,
  maintenance_team_id     integer REFERENCES teams(id),
  status                  text NOT NULL DEFAULT 'active',
  created_at              timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_equipment_team ON equipment (maintenance_team_id);

CREATE TABLE work_centers (
  id                   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name                 text NOT NULL UNIQUE,
  code                 text UNIQUE,
  tag                  text,
  cost_per_hour        double precision NOT NULL DEFAULT 0 CHECK (cost_per_hour >= 0),
  capacity_per_hour    double precision NOT NULL DEFAULT 0 CHECK (capacity_per_hour >= 0),
  time_efficiency_pct  double precision NOT NULL DEFAULT 100 CHECK (time_efficiency_pct BETWEEN 0 AND 100),
  oee_target_pct       double precision NOT NULL DEFAULT 0 CHECK (oee_target_pct BETWEEN 0 AND 100),
  status               text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive'))
);

CREATE TABLE work_center_alternatives (
  id                          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  work_center_id              integer NOT NULL REFERENCES work_centers(id) ON DELETE CASCADE,
  alternative_work_center_id  integer NOT NULL REFERENCES work_centers(id) ON DELETE CASCADE,
  UNIQUE (work_center_id, alternative_work_center_id)
);

-- equipment_id is nullable: a request targets exactly one of equipment or a
-- work centre, which the API enforces.
CREATE TABLE maintenance_requests (
  id                   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type                 text NOT NULL,
  subject              text NOT NULL,
  equipment_id         integer REFERENCES equipment(id),
  work_center_id       integer REFERENCES work_centers(id),
  team_id              integer REFERENCES teams(id),
  scheduled_date       date,
  status               text NOT NULL DEFAULT 'new',
  assigned_to_user_id  integer REFERENCES users(id),
  duration_hours       double precision,
  created_by_user_id   integer NOT NULL REFERENCES users(id),
  created_at           timestamptz NOT NULL DEFAULT now(),
  updated_at           timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_requests_assigned ON maintenance_requests (assigned_to_user_id);
CREATE INDEX idx_requests_created_by ON maintenance_requests (created_by_user_id);
CREATE INDEX idx_requests_status ON maintenance_requests (status);
CREATE INDEX idx_requests_scheduled ON maintenance_requests (scheduled_date);
CREATE INDEX idx_requests_equipment ON maintenance_requests (equipment_id);
CREATE INDEX idx_requests_work_center ON maintenance_requests (work_center_id);

-- created_by_user_id is nullable because notes written before authorship was
-- recorded have no author, and inventing one would put a name against words
-- somebody else wrote.
CREATE TABLE notes (
  id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id          integer NOT NULL REFERENCES maintenance_requests(id) ON DELETE CASCADE,
  message             text NOT NULL,
  created_by_user_id  integer REFERENCES users(id) ON DELETE SET NULL,
  created_at          timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_notes_request ON notes (request_id);
CREATE INDEX idx_notes_author ON notes (created_by_user_id);
